export const skills = [
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Markdown",
  "CSS BEM convention",
  "CSS Grid",
  "CSS Flexbox",
  "JavaScript ES6+",
  "Immutability",
  "React Router",
  "Redux-Saga",
  "Redux (Toolkit)",
  "React",
  "React Hooks",
  "Error handling",
  "Promises, Async/Await",
  "Debugging",
  "NPM",
  "Git",
  "Trello",
  "Teamwork",
  "Scrum",
  "Figma",
  "Working with API (fetch, axios)",
  "GitHub Pull Requests & Review",
];

export const nextSkills = [
  "React Context",
  "Node.js",
  "Unit testing",
  "TypeScript",
  "JS classes",
  "Cypress",
];
